# LogistiX – Enterprise Supply Chain Intelligence Platform

## Notebook 01 — Data Profiling

### Phase
Data Understanding

### Objective

The objective of this notebook is to understand the structure, quality, and characteristics of the raw DataCo Smart Supply Chain dataset before performing any data cleaning, feature engineering, or business analysis.

---

### Workflow

1. Import Libraries
2. Load Dataset
3. Explore Dataset Structure
4. Analyze Columns
5. Check Data Types
6. Analyze Missing Values
7. Detect Duplicates
8. Data Quality Assessment
9. Business Interpretation
10. Next Steps

In [1]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", 1000)

print("LogistiX - Data Profiling Started")

LogistiX - Data Profiling Started

In [2]:
file_path = "../data/raw/DataCoSupplyChainDataset/DataCoSupplyChainDataset.csv"

df = pd.read_csv(file_path, encoding="latin1")

print("Dataset Loaded Successfully")

Dataset Loaded Successfully

In [3]:
rows, columns = df.shape

print(f"Rows    : {rows:,}")
print(f"Columns : {columns}")

Rows    : 180,519
Columns : 53

In [4]:
df.head()

       Type  Days for shipping (real)  Days for shipment (scheduled)  Benefit per order  Sales per customer   Delivery Status  Late_delivery_risk  Category Id   Category Name Customer City Customer Country Customer Email Customer Fname  Customer Id Customer Lname Customer Password Customer Segment Customer State           Customer Street  Customer Zipcode  Department Id Department Name   Latitude   Longitude        Market  Order City Order Country  Order Customer Id order date (DateOrders)  Order Id  Order Item Cardprod Id  Order Item Discount  Order Item Discount Rate  Order Item Id  Order Item Product Price  Order Item Profit Ratio  Order Item Quantity   Sales  Order Item Total  Order Profit Per Order    Order Region      Order State     Order Status  Order Zipcode  Product Card Id  Product Category Id  Product Description                                 Product Image  Product Name  Product Price  Product Status shipping date (DateOrders)   Shipping Mode
0     DEBIT                         3                              4          91.250000          314.640015  Advance shipping                   0           73  Sporting Goods        Caguas      Puerto Rico      XXXXXXXXX          Cally        20755       Holloway         XXXXXXXXX         Consumer             PR  5365 Noble Nectar Island             725.0              2         Fitness  18.251453  -66.037056  Pacific Asia      Bekasi     Indonesia              20755         1/31/2018 22:56     77202                    1360            13.110000                      0.04         180517                    327.75                     0.29                    1  327.75        314.640015               91.250000  Southeast Asia  Java Occidental         COMPLETE            NaN             1360                   73                  NaN  http://images.acmesports.sports/Smart+watch   Smart watch          327.75               0             2/3/2018 22:56  Standard Class
1  TRANSFER                         5                              4        -249.089996          311.359985     Late delivery                   1           73  Sporting Goods        Caguas      Puerto Rico      XXXXXXXXX          Irene        19492           Luna         XXXXXXXXX         Consumer             PR          2679 Rustic Loop             725.0              2         Fitness  18.279451  -66.037064  Pacific Asia     Bikaner         India              19492         1/13/2018 12:27     75939                    1360            16.389999                      0.05         179254                    327.75                    -0.80                    1  327.75        311.359985             -249.089996      South Asia         Rajastán          PENDING            NaN             1360                   73                  NaN  http://images.acmesports.sports/Smart+watch   Smart watch          327.75               0            1/18/2018 12:27  Standard Class
2      CASH                         4                              4        -247.779999          309.720001  Shipping on time                   0           73  Sporting Goods      San Jose          EE. UU.      XXXXXXXXX        Gillian        19491      Maldonado         XXXXXXXXX         Consumer             CA      8510 Round Bear Gate           95125.0              2         Fitness  37.292233 -121.881279  Pacific Asia     Bikaner         India              19491         1/13/2018 12:06     75938                    1360            18.030001                      0.06         179253                    327.75                    -0.80                    1  327.75        309.720001             -247.779999      South Asia         Rajastán           CLOSED            NaN             1360                   73                  NaN  http://images.acmesports.sports/Smart+watch   Smart watch          327.75               0            1/17/2018 12:06  Standard Class
3     DEBIT                         3                              4          22.860001          304.809998  Advance shipping                   0           73  Sporting Goods   Los Angeles          EE. UU.      XXXXXXXXX           Tana        19490           Tate         XXXXXXXXX      Home Office             CA           3200 Amber Bend           90027.0              2         Fitness  34.125946 -118.291016  Pacific Asia  Townsville     Australia              19490         1/13/2018 11:45     75937                    1360            22.940001                      0.07         179252                    327.75                     0.08                    1  327.75        304.809998               22.860001         Oceania       Queensland         COMPLETE            NaN             1360                   73                  NaN  http://images.acmesports.sports/Smart+watch   Smart watch          327.75               0            1/16/2018 11:45  Standard Class
4   PAYMENT                         2                              4         134.210007          298.250000  Advance shipping                   0           73  Sporting Goods        Caguas      Puerto Rico      XXXXXXXXX           Orli        19489      Hendricks         XXXXXXXXX        Corporate             PR  8671 Iron Anchor Corners             725.0              2         Fitness  18.253769  -66.037048  Pacific Asia  Townsville     Australia              19489         1/13/2018 11:24     75936                    1360            29.500000                      0.09         179251                    327.75                     0.45                    1  327.75        298.250000              134.210007         Oceania       Queensland  PENDING_PAYMENT            NaN             1360                   73                  NaN  http://images.acmesports.sports/Smart+watch   Smart watch          327.75               0            1/15/2018 11:24  Standard Class

In [5]:
df.tail()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,Customer Country,Customer Email,Customer Fname,Customer Id,Customer Lname,Customer Password,Customer Segment,Customer State,Customer Street,Customer Zipcode,Department Id,Department Name,Latitude,Longitude,Market,Order City,Order Country,Order Customer Id,order date (DateOrders),Order Id,Order Item Cardprod Id,Order Item Discount,Order Item Discount Rate,Order Item Id,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
180514,CASH,4,4,40.000000,399.980011,Shipping on time,0,45,Fishing,Brooklyn,EE. UU.,XXXXXXXXX,Maria,1005,Peterson,XXXXXXXXX,Home Office,NY,1322 Broad Glade,11207.0,7,Fan Shop,40.640930,-73.942711,Pacific Asia,Shanghái,China,1005,1/16/2016 3:40,26043,1004,0.0,0.00,65177,399.980011,0.10,1,399.980011,399.980011,40.000000,Eastern Asia,Shanghái,CLOSED,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/20/2016 3:40,Standard Class
180515,DEBIT,3,2,-613.770019,395.980011,Late delivery,1,45,Fishing,Bakersfield,EE. UU.,XXXXXXXXX,Ronald,9141,Clark,XXXXXXXXX,Corporate,CA,7330 Broad Apple Moor,93304.0,7,Fan Shop,35.362545,-119.018700,Pacific Asia,Hirakata,Japón,9141,1/16/2016 1:34,26037,1004,4.0,0.01,65161,399.980011,-1.55,1,399.980011,395.980011,-613.770019,Eastern Asia,Osaka,COMPLETE,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/19/2016 1:34,Second Class
180516,TRANSFER,5,4,141.110001,391.980011,Late delivery,1,45,Fishing,Bristol,EE. UU.,XXXXXXXXX,John,291,Smith,XXXXXXXXX,Corporate,CT,97 Burning Landing,6010.0,7,Fan Shop,41.629959,-72.967155,Pacific Asia,Adelaide,Australia,291,1/15/2016 21:00,26024,1004,8.0,0.02,65129,399.980011,0.36,1,399.980011,391.980011,141.110001,Oceania,Australia del Sur,PENDING,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/20/2016 21:00,Standard Class
180517,PAYMENT,3,4,186.229996,387.980011,Advance shipping,0,45,Fishing,Caguas,Puerto Rico,XXXXXXXXX,Mary,2813,Smith,XXXXXXXXX,Consumer,PR,2585 Silent Autumn Landing,725.0,7,Fan Shop,18.213350,-66.370575,Pacific Asia,Adelaide,Australia,2813,1/15/2016 20:18,26022,1004,12.0,0.03,65126,399.980011,0.48,1,399.980011,387.980011,186.229996,Oceania,Australia del Sur,PENDING_PAYMENT,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/18/2016 20:18,Standard Class
180518,PAYMENT,4,4,168.949997,383.980011,Shipping on time,0,45,Fishing,Caguas,Puerto Rico,XXXXXXXXX,Andrea,7547,Ortega,XXXXXXXXX,Consumer,PR,697 Little Meadow,725.0,7,Fan Shop,18.290380,-66.370613,Pacific Asia,Nagercoil,India,7547,1/15/2016 18:54,26018,1004,16.0,0.04,65113,399.980011,0.44,1,399.980011,383.980011,168.949997,South Asia,Tamil Nadu,PENDING_PAYMENT,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/19/2016 18:54,Standard Class

In [6]:
df.sample(5)

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,Customer Country,Customer Email,Customer Fname,Customer Id,Customer Lname,Customer Password,Customer Segment,Customer State,Customer Street,Customer Zipcode,Department Id,Department Name,Latitude,Longitude,Market,Order City,Order Country,Order Customer Id,order date (DateOrders),Order Id,Order Item Cardprod Id,Order Item Discount,Order Item Discount Rate,Order Item Id,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
91351,PAYMENT,5,4,46.560001,96.989998,Late delivery,1,9,Cardio Equipment,Caguas,Puerto Rico,XXXXXXXXX,Mary,34,Smith,XXXXXXXXX,Corporate,PR,3330 Easy Berry Range,725.0,3,Footwear,18.146578,-66.277222,USCA,London,Canada,34,1/4/2017 5:37,50299,191,3.000000,0.03,125690,99.989998,0.48,1,99.989998,96.989998,46.560001,Canada,Ontario,PENDING_PAYMENT,NaN,191,9,NaN,http://images.acmesports.sports/Nike+Men%27s+F...,Nike Men's Free 5.0+ Running Shoe,99.989998,0,1/9/2017 5:37,Standard Class
101954,PAYMENT,6,4,85.559998,185.990005,Late delivery,1,48,Water Sports,Pomona,EE. UU.,XXXXXXXXX,Julia,1093,Bowers,XXXXXXXXX,Corporate,CA,1777 Old Willow Stead,91766.0,7,Fan Shop,34.049919,-117.716103,Pacific Asia,Mackay,Australia,1093,12/14/2015 13:21,23810,1073,14.000000,0.07,59579,199.990005,0.46,1,199.990005,185.990005,85.559998,Oceania,Queensland,PENDING_PAYMENT,NaN,1073,48,NaN,http://images.acmesports.sports/Pelican+Sunstr...,Pelican Sunstream 100 Kayak,199.990005,0,12/20/2015 13:21,Standard Class
89411,PAYMENT,5,4,21.350000,188.979996,Late delivery,1,9,Cardio Equipment,Irwin,EE. UU.,XXXXXXXXX,Peter,658,Farley,XXXXXXXXX,Consumer,PA,8771 Middle Quail Heath,15642.0,3,Footwear,39.799999,-76.313599,Africa,Port Elizabeth,SudAfrica,658,8/30/2016 7:23,41604,191,11.000000,0.06,103846,99.989998,0.11,2,199.979996,188.979996,21.350000,Southern Africa,Cabo Oriental,PENDING_PAYMENT,NaN,191,9,NaN,http://images.acmesports.sports/Nike+Men%27s+F...,Nike Men's Free 5.0+ Running Shoe,99.989998,0,9/4/2016 7:23,Standard Class
9988,TRANSFER,3,4,93.940002,208.770004,Advance shipping,0,17,Cleats,Littleton,EE. UU.,XXXXXXXXX,Catherine,1385,Smith,XXXXXXXXX,Corporate,CO,174 Hazy Pines,80126.0,4,Apparel,39.522995,-104.948219,Europe,Sesto San Giovanni,Italia,1385,6/15/2015 18:30,11357,365,31.190001,0.13,28412,59.990002,0.45,4,239.960007,208.770004,93.940002,Southern Europe,Lombardía,PROCESSING,NaN,365,17,NaN,http://images.acmesports.sports/Perfect+Fitnes...,Perfect Fitness Perfect Rip Deck,59.990002,0,6/18/2015 18:30,Standard Class
148449,DEBIT,2,4,4.990000,124.790001,Advance shipping,0,18,Men's Footwear,Caguas,Puerto Rico,XXXXXXXXX,James,8027,Smith,XXXXXXXXX,Home Office,PR,9451 Bright Walk,725.0,4,Apparel,18.266670,-66.370621,Europe,Greifswald,Alemania,8027,9/12/2017 1:14,67481,403,5.200000,0.04,168691,129.990005,0.04,1,129.990005,124.790001,4.990000,Western Europe,Mecklemburgo-Pomerania Occidental,COMPLETE,NaN,403,18,NaN,http://images.acmesports.sports/Nike+Men%27s+C...,Nike Men's CJ Elite 2 TD Football Cleat,129.990005,0,9/14/2017 1:14,Standard Class

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Email                 180519 non-null  object
 12  Customer Fname                 180519 non-null  object
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  object
 15  Customer Password              180519 non-null  object
 16  Customer Segment               180519 non-null  object
 17  Customer State                 180519 non-null  object
 18  Customer Street                180519 non-null  object
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  object
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  object
 25  Order City                     180519 non-null  object
 26  Order Country                  180519 non-null  object
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  object
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  object
 41  Order State                    180519 non-null  object
 42  Order Status                   180519 non-null  object
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  object
 48  Product Name                   180519 non-null  object
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  object
 52  Shipping Mode                  180519 non-null  object
dtypes: float64(15), int64(14), object(24)
memory usage: 73.0+ MB

In [8]:
df.columns.tolist()

['Type',
 'Days for shipping (real)',
 'Days for shipment (scheduled)',
 'Benefit per order',
 'Sales per customer',
 'Delivery Status',
 'Late_delivery_risk',
 'Category Id',
 'Category Name',
 'Customer City',
 'Customer Country',
 'Customer Email',
 'Customer Fname',
 'Customer Id',
 'Customer Lname',
 'Customer Password',
 'Customer Segment',
 'Customer State',
 'Customer Street',
 'Customer Zipcode',
 'Department Id',
 'Department Name',
 'Latitude',
 'Longitude',
 'Market',
 'Order City',
 'Order Country',
 'Order Customer Id',
 'order date (DateOrders)',
 'Order Id',
 'Order Item Cardprod Id',
 'Order Item Discount',
 'Order Item Discount Rate',
 'Order Item Id',
 'Order Item Product Price',
 'Order Item Profit Ratio',
 'Order Item Quantity',
 'Sales',
 'Order Item Total',
 'Order Profit Per Order',
 'Order Region',
 'Order State',
 'Order Status',
 'Order Zipcode',
 'Product Card Id',
 'Product Category Id',
 'Product Description',
 'Product Image',
 'Product Name',
 'Product Price',
 'Product Status',
 'shipping date (DateOrders)',
 'Shipping Mode']

In [9]:
df.dtypes

Type                              object
Days for shipping (real)           int64
Days for shipment (scheduled)      int64
Benefit per order                float64
Sales per customer               float64
Delivery Status                   object
Late_delivery_risk                 int64
Category Id                        int64
Category Name                     object
Customer City                     object
Customer Country                  object
Customer Email                    object
Customer Fname                    object
Customer Id                        int64
Customer Lname                    object
Customer Password                 object
Customer Segment                  object
Customer State                    object
Customer Street                   object
Customer Zipcode                 float64
Department Id                      int64
Department Name                   object
Latitude                         float64
Longitude                        float64
Market                            object
Order City                        object
Order Country                     object
Order Customer Id                  int64
order date (DateOrders)           object
Order Id                           int64
Order Item Cardprod Id             int64
Order Item Discount              float64
Order Item Discount Rate         float64
Order Item Id                      int64
Order Item Product Price         float64
Order Item Profit Ratio          float64
Order Item Quantity                int64
Sales                            float64
Order Item Total                 float64
Order Profit Per Order           float64
Order Region                      object
Order State                       object
Order Status                      object
Order Zipcode                    float64
Product Card Id                    int64
Product Category Id                int64
Product Description              float64
Product Image                     object
Product Name                      object
Product Price                    float64
Product Status                     int64
shipping date (DateOrders)        object
Shipping Mode                     object
dtype: object

In [10]:
df.describe().T

                                  count          mean           std          min           25%           50%            75%            max
Days for shipping (real)       180519.0      3.497654      1.623722     0.000000      2.000000      3.000000       5.000000       6.000000
Days for shipment (scheduled)  180519.0      2.931847      1.374449     0.000000      2.000000      4.000000       4.000000       4.000000
Benefit per order              180519.0     21.974989    104.433526 -4274.979980      7.000000     31.520000      64.800003     911.799988
Sales per customer             180519.0    183.107609    120.043670     7.490000    104.379997    163.990005     247.399994    1939.989990
Late_delivery_risk             180519.0      0.548291      0.497664     0.000000      0.000000      1.000000       1.000000       1.000000
Category Id                    180519.0     31.851451     15.640064     2.000000     18.000000     29.000000      45.000000      76.000000
Customer Id                    180519.0   6691.379495   4162.918106     1.000000   3258.500000   6457.000000    9779.000000   20757.000000
Customer Zipcode               180516.0  35921.126914  37542.461122   603.000000    725.000000  19380.000000   78207.000000   99205.000000
Department Id                  180519.0      5.443460      1.629246     2.000000      4.000000      5.000000       7.000000      12.000000
Latitude                       180519.0     29.719955      9.813646   -33.937553     18.265432     33.144863      39.279617      48.781933
Longitude                      180519.0    -84.915675     21.433241  -158.025986    -98.446312    -76.847908     -66.370583     115.263077
Order Customer Id              180519.0   6691.379495   4162.918106     1.000000   3258.500000   6457.000000    9779.000000   20757.000000
Order Id                       180519.0  36221.894903  21045.379569     1.000000  18057.000000  36140.000000   54144.000000   77204.000000
Order Item Cardprod Id         180519.0    692.509764    336.446807    19.000000    403.000000    627.000000    1004.000000    1363.000000
Order Item Discount            180519.0     20.664741     21.800901     0.000000      5.400000     14.000000      29.990000     500.000000
Order Item Discount Rate       180519.0      0.101668      0.070415     0.000000      0.040000      0.100000       0.160000       0.250000
Order Item Id                  180519.0  90260.000000  52111.490959     1.000000  45130.500000  90260.000000  135389.500000  180519.000000
Order Item Product Price       180519.0    141.232550    139.732492     9.990000     50.000000     59.990002     199.990005    1999.989990
Order Item Profit Ratio        180519.0      0.120647      0.466796    -2.750000      0.080000      0.270000       0.360000       0.500000
Order Item Quantity            180519.0      2.127638      1.453451     1.000000      1.000000      1.000000       3.000000       5.000000
Sales                          180519.0    203.772096    132.273077     9.990000    119.980003    199.919998     299.950012    1999.989990
Order Item Total               180519.0    183.107609    120.043670     7.490000    104.379997    163.990005     247.399994    1939.989990
Order Profit Per Order         180519.0     21.974989    104.433526 -4274.979980      7.000000     31.520000      64.800003     911.799988
Order Zipcode                   24840.0  55426.132327  31919.279101  1040.000000  23464.000000  59405.000000   90008.000000   99301.000000
Product Card Id                180519.0    692.509764    336.446807    19.000000    403.000000    627.000000    1004.000000    1363.000000
Product Category Id            180519.0     31.851451     15.640064     2.000000     18.000000     29.000000      45.000000      76.000000
Product Description                 0.0           NaN           NaN          NaN           NaN           NaN            NaN            NaN
Product Price                  180519.0    141.232550    139.732492     9.990000     50.000000     59.990002     199.990005    1999.989990
Product Status                 180519.0      0.000000      0.000000     0.000000      0.000000      0.000000       0.000000       0.000000

In [11]:
df.describe(include="object").T

                             count unique                                                top    freq
Type                        180519      4                                              DEBIT   69295
Delivery Status             180519      4                                      Late delivery   98977
Category Name               180519     50                                             Cleats   24551
Customer City               180519    563                                             Caguas   66770
Customer Country            180519      2                                            EE. UU.  111146
Customer Email              180519      1                                          XXXXXXXXX  180519
Customer Fname              180519    782                                               Mary   65150
Customer Lname              180511   1109                                              Smith   64104
Customer Password           180519      1                                          XXXXXXXXX  180519
Customer Segment            180519      3                                           Consumer   93504
Customer State              180519     46                                                 PR   69373
Customer Street             180519   7458                            9126 Wishing Expressway     122
Department Name             180519     11                                           Fan Shop   66861
Market                      180519      5                                              LATAM   51594
Order City                  180519   3597                                      Santo Domingo    2211
Order Country               180519    164                                     Estados Unidos   24840
order date (DateOrders)     180519  65752                                   12/14/2016 12:29       5
Order Region                180519     23                                    Central America   28341
Order State                 180519   1089                                         Inglaterra    6722
Order Status                180519      9                                           COMPLETE   59491
Product Image               180519    118  http://images.acmesports.sports/Perfect+Fitnes...   24515
Product Name                180519    118                   Perfect Fitness Perfect Rip Deck   24515
shipping date (DateOrders)  180519  63701                                      1/5/2016 5:58      10
Shipping Mode               180519      4                                     Standard Class  107752

In [12]:
missing = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Missing Percentage": (df.isnull().sum()/len(df)*100).round(2)
})

missing.sort_values("Missing Percentage", ascending=False)

                               Missing Values  Missing Percentage
Product Description                    180519              100.00
Order Zipcode                          155679               86.24
Type                                        0                0.00
Order Profit Per Order                      0                0.00
Order Id                                    0                0.00
Order Item Cardprod Id                      0                0.00
Order Item Discount                         0                0.00
Order Item Discount Rate                    0                0.00
Order Item Id                               0                0.00
Order Item Product Price                    0                0.00
Order Item Profit Ratio                     0                0.00
Order Item Quantity                         0                0.00
Sales                                       0                0.00
Order Item Total                            0                0.00
Order Region                                0                0.00
Order Customer Id                           0                0.00
Order State                                 0                0.00
Order Status                                0                0.00
Product Card Id                             0                0.00
Product Category Id                         0                0.00
Product Image                               0                0.00
Product Name                                0                0.00
Product Price                               0                0.00
Product Status                              0                0.00
shipping date (DateOrders)                  0                0.00
order date (DateOrders)                     0                0.00
Order Country                               0                0.00
Days for shipping (real)                    0                0.00
Order City                                  0                0.00
Days for shipment (scheduled)               0                0.00
Benefit per order                           0                0.00
Sales per customer                          0                0.00
Delivery Status                             0                0.00
Late_delivery_risk                          0                0.00
Category Id                                 0                0.00
Category Name                               0                0.00
Customer City                               0                0.00
Customer Country                            0                0.00
Customer Email                              0                0.00
Customer Fname                              0                0.00
Customer Id                                 0                0.00
Customer Lname                              8                0.00
Customer Password                           0                0.00
Customer Segment                            0                0.00
Customer State                              0                0.00
Customer Street                             0                0.00
Customer Zipcode                            3                0.00
Department Id                               0                0.00
Department Name                             0                0.00
Latitude                                    0                0.00
Longitude                                   0                0.00
Market                                      0                0.00
Shipping Mode                               0                0.00

In [13]:
df.isnull().sum().sum()

np.int64(336209)

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df.nunique().sort_values()

Product Description                   0
Product Status                        1
Customer Password                     1
Customer Email                        1
Late_delivery_risk                    2
Customer Country                      2
Customer Segment                      3
Type                                  4
Shipping Mode                         4
Delivery Status                       4
Days for shipment (scheduled)         4
Order Item Quantity                   5
Market                                5
Days for shipping (real)              7
Order Status                          9
Department Id                        11
Department Name                      11
Order Item Discount Rate             18
Order Region                         23
Customer State                       46
Category Name                        50
Category Id                          51
Product Category Id                  51
Product Price                        75
Order Item Product Price             75
Order Item Cardprod Id              118
Product Name                        118
Product Image                       118
Product Card Id                     118
Order Item Profit Ratio             162
Order Country                       164
Sales                               193
Customer City                       563
Order Zipcode                       609
Customer Fname                      782
Customer Zipcode                    995
Order Item Discount                1017
Order State                        1089
Customer Lname                     1109
Order Item Total                   2927
Sales per customer                 2927
Order City                         3597
Longitude                          4487
Customer Street                    7458
Latitude                          11250
Order Customer Id                 20652
Customer Id                       20652
Order Profit Per Order            21998
Benefit per order                 21998
shipping date (DateOrders)        63701
Order Id                          65752
order date (DateOrders)           65752
Order Item Id                    180519
dtype: int64

In [16]:
df.memory_usage(deep=True)

Index                                 132
Type                              9961509
Days for shipping (real)          1444152
Days for shipment (scheduled)     1444152
Benefit per order                 1444152
Sales per customer                1444152
Delivery Status                  11444558
Late_delivery_risk                1444152
Category Id                       1444152
Category Name                    11139429
Customer City                    10236984
Customer Country                 10386556
Customer Email                   10470102
Customer Fname                    9797607
Customer Id                       1444152
Customer Lname                    9876448
Customer Password                10470102
Customer Segment                 10441050
Customer State                    9206478
Customer Street                  12448069
Customer Zipcode                  1444152
Department Id                     1444152
Department Name                  10116233
Latitude                          1444152
Longitude                         1444152
Market                           10072913
Order City                       10799565
Order Country                    11429783
Order Customer Id                 1444152
order date (DateOrders)          11462774
Order Id                          1444152
Order Item Cardprod Id            1444152
Order Item Discount               1444152
Order Item Discount Rate          1444152
Order Item Id                     1444152
Order Item Product Price          1444152
Order Item Profit Ratio           1444152
Order Item Quantity               1444152
Sales                             1444152
Order Item Total                  1444152
Order Profit Per Order            1444152
Order Region                     11126163
Order State                      11874020
Order Status                     10582740
Order Zipcode                     1444152
Product Card Id                   1444152
Product Category Id               1444152
Product Description               1444152
Product Image                    21472196
Product Name                     15185259
Product Price                     1444152
Product Status                    1444152
shipping date (DateOrders)       11463307
Shipping Mode                    11160401
dtype: int64

In [17]:
df.memory_usage(deep=True).sum() / 1024**2

np.float64(299.93513679504395)

In [18]:
pd.DataFrame({
    "Data Type": df.dtypes,
    "Unique Values": df.nunique(),
    "Missing Values": df.isnull().sum()
})

                              Data Type  Unique Values  Missing Values
Type                             object              4               0
Days for shipping (real)          int64              7               0
Days for shipment (scheduled)     int64              4               0
Benefit per order               float64          21998               0
Sales per customer              float64           2927               0
Delivery Status                  object              4               0
Late_delivery_risk                int64              2               0
Category Id                       int64             51               0
Category Name                    object             50               0
Customer City                    object            563               0
Customer Country                 object              2               0
Customer Email                   object              1               0
Customer Fname                   object            782               0
Customer Id                       int64          20652               0
Customer Lname                   object           1109               8
Customer Password                object              1               0
Customer Segment                 object              3               0
Customer State                   object             46               0
Customer Street                  object           7458               0
Customer Zipcode                float64            995               3
Department Id                     int64             11               0
Department Name                  object             11               0
Latitude                        float64          11250               0
Longitude                       float64           4487               0
Market                           object              5               0
Order City                       object           3597               0
Order Country                    object            164               0
Order Customer Id                 int64          20652               0
order date (DateOrders)          object          65752               0
Order Id                          int64          65752               0
Order Item Cardprod Id            int64            118               0
Order Item Discount             float64           1017               0
Order Item Discount Rate        float64             18               0
Order Item Id                     int64         180519               0
Order Item Product Price        float64             75               0
Order Item Profit Ratio         float64            162               0
Order Item Quantity               int64              5               0
Sales                           float64            193               0
Order Item Total                float64           2927               0
Order Profit Per Order          float64          21998               0
Order Region                     object             23               0
Order State                      object           1089               0
Order Status                     object              9               0
Order Zipcode                   float64            609          155679
Product Card Id                   int64            118               0
Product Category Id               int64             51               0
Product Description             float64              0          180519
Product Image                    object            118               0
Product Name                     object            118               0
Product Price                   float64             75               0
Product Status                    int64              1               0
shipping date (DateOrders)       object          63701               0
Shipping Mode                    object              4               0

In [19]:
categorical_columns = df.select_dtypes(include="object").columns

categorical_columns

Index(['Type', 'Delivery Status', 'Category Name', 'Customer City', 'Customer Country', 'Customer Email', 'Customer Fname', 'Customer Lname', 'Customer Password', 'Customer Segment', 'Customer State', 'Customer Street', 'Department Name', 'Market', 'Order City', 'Order Country', 'order date (DateOrders)', 'Order Region', 'Order State', 'Order Status', 'Product Image', 'Product Name', 'shipping date (DateOrders)', 'Shipping Mode'], dtype='object')

In [20]:
numerical_columns = df.select_dtypes(exclude="object").columns

numerical_columns

Index(['Days for shipping (real)', 'Days for shipment (scheduled)', 'Benefit per order', 'Sales per customer', 'Late_delivery_risk', 'Category Id', 'Customer Id', 'Customer Zipcode', 'Department Id', 'Latitude', 'Longitude', 'Order Customer Id', 'Order Id', 'Order Item Cardprod Id', 'Order Item Discount', 'Order Item Discount Rate', 'Order Item Id', 'Order Item Product Price', 'Order Item Profit Ratio', 'Order Item Quantity', 'Sales', 'Order Item Total', 'Order Profit Per Order', 'Order Zipcode', 'Product Card Id', 'Product Category Id', 'Product Description', 'Product Price', 'Product Status'], dtype='object')

In [21]:
date_columns = [col for col in df.columns if "date" in col.lower()]

date_columns

['order date (DateOrders)', 'shipping date (DateOrders)']

# Business Interpretation

### Key Findings

- Dataset loaded successfully.
- Dataset structure has been explored.
- Data types have been identified.
- Missing values have been quantified.
- Duplicate records have been checked.
- Numerical and categorical columns have been separated.
- Initial data quality assessment has been completed.

---

### Next Phase

The next notebook focuses on **Data Cleaning**, where missing values, inconsistent records, duplicate entries, incorrect data types, and other data quality issues will be resolved before analysis.

# Column Understanding

The objective of this section is to understand the business meaning of every column in the dataset before performing any transformations. This helps ensure accurate data cleaning, feature engineering, SQL analysis, and dashboard development.

In [22]:
pd.DataFrame({
    "Column Name": df.columns,
    "Data Type": df.dtypes.values,
    "Missing Values": df.isnull().sum().values,
    "Unique Values": df.nunique().values
})

                      Column Name Data Type  Missing Values  Unique Values
0                            Type    object               0              4
1        Days for shipping (real)     int64               0              7
2   Days for shipment (scheduled)     int64               0              4
3               Benefit per order   float64               0          21998
4              Sales per customer   float64               0           2927
5                 Delivery Status    object               0              4
6              Late_delivery_risk     int64               0              2
7                     Category Id     int64               0             51
8                   Category Name    object               0             50
9                   Customer City    object               0            563
10               Customer Country    object               0              2
11                 Customer Email    object               0              1
12                 Customer Fname    object               0            782
13                    Customer Id     int64               0          20652
14                 Customer Lname    object               8           1109
15              Customer Password    object               0              1
16               Customer Segment    object               0              3
17                 Customer State    object               0             46
18                Customer Street    object               0           7458
19               Customer Zipcode   float64               3            995
20                  Department Id     int64               0             11
21                Department Name    object               0             11
22                       Latitude   float64               0          11250
23                      Longitude   float64               0           4487
24                         Market    object               0              5
25                     Order City    object               0           3597
26                  Order Country    object               0            164
27              Order Customer Id     int64               0          20652
28        order date (DateOrders)    object               0          65752
29                       Order Id     int64               0          65752
30         Order Item Cardprod Id     int64               0            118
31            Order Item Discount   float64               0           1017
32       Order Item Discount Rate   float64               0             18
33                  Order Item Id     int64               0         180519
34       Order Item Product Price   float64               0             75
35        Order Item Profit Ratio   float64               0            162
36            Order Item Quantity     int64               0              5
37                          Sales   float64               0            193
38               Order Item Total   float64               0           2927
39         Order Profit Per Order   float64               0          21998
40                   Order Region    object               0             23
41                    Order State    object               0           1089
42                   Order Status    object               0              9
43                  Order Zipcode   float64          155679            609
44                Product Card Id     int64               0            118
45            Product Category Id     int64               0             51
46            Product Description   float64          180519              0
47                  Product Image    object               0            118
48                   Product Name    object               0            118
49                  Product Price   float64               0             75
50                 Product Status     int64               0              1
51     shipping date (DateOrders)    object               0          63701
52                  Shipping Mode    object               0              4

In [23]:
column_summary = pd.DataFrame({
    "Column Name": df.columns,
    "Data Type": df.dtypes.values,
    "Missing Values": df.isnull().sum().values,
    "Missing Percentage": (df.isnull().sum()/len(df)*100).round(2).values,
    "Unique Values": df.nunique().values
})

column_summary

                      Column Name Data Type  Missing Values  Missing Percentage  Unique Values
0                            Type    object               0                0.00              4
1        Days for shipping (real)     int64               0                0.00              7
2   Days for shipment (scheduled)     int64               0                0.00              4
3               Benefit per order   float64               0                0.00          21998
4              Sales per customer   float64               0                0.00           2927
5                 Delivery Status    object               0                0.00              4
6              Late_delivery_risk     int64               0                0.00              2
7                     Category Id     int64               0                0.00             51
8                   Category Name    object               0                0.00             50
9                   Customer City    object               0                0.00            563
10               Customer Country    object               0                0.00              2
11                 Customer Email    object               0                0.00              1
12                 Customer Fname    object               0                0.00            782
13                    Customer Id     int64               0                0.00          20652
14                 Customer Lname    object               8                0.00           1109
15              Customer Password    object               0                0.00              1
16               Customer Segment    object               0                0.00              3
17                 Customer State    object               0                0.00             46
18                Customer Street    object               0                0.00           7458
19               Customer Zipcode   float64               3                0.00            995
20                  Department Id     int64               0                0.00             11
21                Department Name    object               0                0.00             11
22                       Latitude   float64               0                0.00          11250
23                      Longitude   float64               0                0.00           4487
24                         Market    object               0                0.00              5
25                     Order City    object               0                0.00           3597
26                  Order Country    object               0                0.00            164
27              Order Customer Id     int64               0                0.00          20652
28        order date (DateOrders)    object               0                0.00          65752
29                       Order Id     int64               0                0.00          65752
30         Order Item Cardprod Id     int64               0                0.00            118
31            Order Item Discount   float64               0                0.00           1017
32       Order Item Discount Rate   float64               0                0.00             18
33                  Order Item Id     int64               0                0.00         180519
34       Order Item Product Price   float64               0                0.00             75
35        Order Item Profit Ratio   float64               0                0.00            162
36            Order Item Quantity     int64               0                0.00              5
37                          Sales   float64               0                0.00            193
38               Order Item Total   float64               0                0.00           2927
39         Order Profit Per Order   float64               0                0.00          21998
40                   Order Region    object               0                0.00             23
41                    Order State    object               0                0.00           1089
42                   Order Status    object               0                0.00              9
43                  Order Zipcode   float64          155679               86.24            609
44                Product Card Id     int64               0                0.00            118
45            Product Category Id     int64               0                0.00             51
46            Product Description   float64          180519              100.00              0
47                  Product Image    object               0                0.00            118
48                   Product Name    object               0                0.00            118
49                  Product Price   float64               0                0.00             75
50                 Product Status     int64               0                0.00              1
51     shipping date (DateOrders)    object               0                0.00          63701
52                  Shipping Mode    object               0                0.00              4

In [24]:
column_summary.sort_values("Missing Percentage", ascending=False)

                      Column Name Data Type  Missing Values  Missing Percentage  Unique Values
46            Product Description   float64          180519              100.00              0
43                  Order Zipcode   float64          155679               86.24            609
0                            Type    object               0                0.00              4
39         Order Profit Per Order   float64               0                0.00          21998
29                       Order Id     int64               0                0.00          65752
30         Order Item Cardprod Id     int64               0                0.00            118
31            Order Item Discount   float64               0                0.00           1017
32       Order Item Discount Rate   float64               0                0.00             18
33                  Order Item Id     int64               0                0.00         180519
34       Order Item Product Price   float64               0                0.00             75
35        Order Item Profit Ratio   float64               0                0.00            162
36            Order Item Quantity     int64               0                0.00              5
37                          Sales   float64               0                0.00            193
38               Order Item Total   float64               0                0.00           2927
40                   Order Region    object               0                0.00             23
27              Order Customer Id     int64               0                0.00          20652
41                    Order State    object               0                0.00           1089
42                   Order Status    object               0                0.00              9
44                Product Card Id     int64               0                0.00            118
45            Product Category Id     int64               0                0.00             51
47                  Product Image    object               0                0.00            118
48                   Product Name    object               0                0.00            118
49                  Product Price   float64               0                0.00             75
50                 Product Status     int64               0                0.00              1
51     shipping date (DateOrders)    object               0                0.00          63701
28        order date (DateOrders)    object               0                0.00          65752
26                  Order Country    object               0                0.00            164
1        Days for shipping (real)     int64               0                0.00              7
25                     Order City    object               0                0.00           3597
2   Days for shipment (scheduled)     int64               0                0.00              4
3               Benefit per order   float64               0                0.00          21998
4              Sales per customer   float64               0                0.00           2927
5                 Delivery Status    object               0                0.00              4
6              Late_delivery_risk     int64               0                0.00              2
7                     Category Id     int64               0                0.00             51
8                   Category Name    object               0                0.00             50
9                   Customer City    object               0                0.00            563
10               Customer Country    object               0                0.00              2
11                 Customer Email    object               0                0.00              1
12                 Customer Fname    object               0                0.00            782
13                    Customer Id     int64               0                0.00          20652
14                 Customer Lname    object               8                0.00           1109
15              Customer Password    object               0                0.00              1
16               Customer Segment    object               0                0.00              3
17                 Customer State    object               0                0.00             46
18                Customer Street    object               0                0.00           7458
19               Customer Zipcode   float64               3                0.00            995
20                  Department Id     int64               0                0.00             11
21                Department Name    object               0                0.00             11
22                       Latitude   float64               0                0.00          11250
23                      Longitude   float64               0                0.00           4487
24                         Market    object               0                0.00              5
52                  Shipping Mode    object               0                0.00              4

In [25]:
column_summary.sort_values("Unique Values")

                      Column Name Data Type  Missing Values  Missing Percentage  Unique Values
46            Product Description   float64          180519              100.00              0
50                 Product Status     int64               0                0.00              1
15              Customer Password    object               0                0.00              1
11                 Customer Email    object               0                0.00              1
6              Late_delivery_risk     int64               0                0.00              2
10               Customer Country    object               0                0.00              2
16               Customer Segment    object               0                0.00              3
0                            Type    object               0                0.00              4
52                  Shipping Mode    object               0                0.00              4
5                 Delivery Status    object               0                0.00              4
2   Days for shipment (scheduled)     int64               0                0.00              4
36            Order Item Quantity     int64               0                0.00              5
24                         Market    object               0                0.00              5
1        Days for shipping (real)     int64               0                0.00              7
42                   Order Status    object               0                0.00              9
20                  Department Id     int64               0                0.00             11
21                Department Name    object               0                0.00             11
32       Order Item Discount Rate   float64               0                0.00             18
40                   Order Region    object               0                0.00             23
17                 Customer State    object               0                0.00             46
8                   Category Name    object               0                0.00             50
7                     Category Id     int64               0                0.00             51
45            Product Category Id     int64               0                0.00             51
49                  Product Price   float64               0                0.00             75
34       Order Item Product Price   float64               0                0.00             75
30         Order Item Cardprod Id     int64               0                0.00            118
48                   Product Name    object               0                0.00            118
47                  Product Image    object               0                0.00            118
44                Product Card Id     int64               0                0.00            118
35        Order Item Profit Ratio   float64               0                0.00            162
26                  Order Country    object               0                0.00            164
37                          Sales   float64               0                0.00            193
9                   Customer City    object               0                0.00            563
43                  Order Zipcode   float64          155679               86.24            609
12                 Customer Fname    object               0                0.00            782
19               Customer Zipcode   float64               3                0.00            995
31            Order Item Discount   float64               0                0.00           1017
41                    Order State    object               0                0.00           1089
14                 Customer Lname    object               8                0.00           1109
38               Order Item Total   float64               0                0.00           2927
4              Sales per customer   float64               0                0.00           2927
25                     Order City    object               0                0.00           3597
23                      Longitude   float64               0                0.00           4487
18                Customer Street    object               0                0.00           7458
22                       Latitude   float64               0                0.00          11250
27              Order Customer Id     int64               0                0.00          20652
13                    Customer Id     int64               0                0.00          20652
39         Order Profit Per Order   float64               0                0.00          21998
3               Benefit per order   float64               0                0.00          21998
51     shipping date (DateOrders)    object               0                0.00          63701
29                       Order Id     int64               0                0.00          65752
28        order date (DateOrders)    object               0                0.00          65752
33                  Order Item Id     int64               0                0.00         180519

# Dataset Quality Summary

This summary provides an overview of the dataset quality before any preprocessing activities.

In [27]:
quality_report = pd.DataFrame({
    "Metric": [
        "Rows",
        "Columns",
        "Duplicate Rows",
        "Total Missing Values",
        "Numerical Columns",
        "Categorical Columns"
    ],
    "Value": [
        len(df),
        len(df.columns),
        df.duplicated().sum(),
        df.isnull().sum().sum(),
        len(df.select_dtypes(exclude="object").columns),
        len(df.select_dtypes(include="object").columns)
    ]
})

quality_report

                 Metric   Value
0                  Rows  180519
1               Columns      53
2        Duplicate Rows       0
3  Total Missing Values  336209
4     Numerical Columns      29
5   Categorical Columns      24

# Conclusion

The raw dataset has been successfully profiled and assessed. The analysis identified the overall structure, column information, missing values, duplicate records, data types, and general data quality characteristics.

The next phase will focus on data cleaning, where identified quality issues will be addressed before performing feature engineering and exploratory data analysis.