# LogistiX – Enterprise Supply Chain Intelligence Platform

## Notebook 02 — Data Cleaning

### Phase

Data Preparation

### Objective

The objective of this notebook is to clean and preprocess the raw DataCo Smart Supply Chain dataset by handling missing values, correcting data types, removing duplicate records, validating business rules, and preparing a high-quality dataset for feature engineering and analysis.

---

### Workflow

1. Import Libraries
2. Load Dataset
3. Create Working Copy
4. Standardize Column Names
5. Check Missing Values
6. Handle Duplicates
7. Validate Data Types
8. Clean Text Columns
9. Validate Business Rules
10. Export Cleaned Dataset

In [1]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)

print("LogistiX - Data Cleaning Started")

LogistiX - Data Cleaning Started

In [2]:
file_path = "../data/raw/DataCoSupplyChainDataset/DataCoSupplyChainDataset.csv"

df = pd.read_csv(file_path, encoding="latin1")

print(df.shape)

(180519, 53)

In [3]:
clean_df = df.copy()

print(clean_df.shape)

(180519, 53)

In [4]:
clean_df.head()

       Type  Days for shipping (real)  Days for shipment (scheduled)  Benefit per order  Sales per customer   Delivery Status  Late_delivery_risk  Category Id   Category Name Customer City Customer Country Customer Email Customer Fname  Customer Id Customer Lname Customer Password Customer Segment Customer State           Customer Street  Customer Zipcode  Department Id Department Name   Latitude   Longitude        Market  Order City Order Country  Order Customer Id order date (DateOrders)  Order Id  Order Item Cardprod Id  Order Item Discount  Order Item Discount Rate  Order Item Id  Order Item Product Price  Order Item Profit Ratio  Order Item Quantity   Sales  Order Item Total  Order Profit Per Order    Order Region      Order State     Order Status  Order Zipcode  Product Card Id  Product Category Id  Product Description                                 Product Image  Product Name  Product Price  Product Status shipping date (DateOrders)   Shipping Mode
0     DEBIT                         3                              4          91.250000          314.640015  Advance shipping                   0           73  Sporting Goods        Caguas      Puerto Rico      XXXXXXXXX          Cally        20755       Holloway         XXXXXXXXX         Consumer             PR  5365 Noble Nectar Island             725.0              2         Fitness  18.251453  -66.037056  Pacific Asia      Bekasi     Indonesia              20755         1/31/2018 22:56     77202                    1360            13.110000                      0.04         180517                    327.75                     0.29                    1  327.75        314.640015               91.250000  Southeast Asia  Java Occidental         COMPLETE            NaN             1360                   73                  NaN  http://images.acmesports.sports/Smart+watch   Smart watch          327.75               0             2/3/2018 22:56  Standard Class
1  TRANSFER                         5                              4        -249.089996          311.359985     Late delivery                   1           73  Sporting Goods        Caguas      Puerto Rico      XXXXXXXXX          Irene        19492           Luna         XXXXXXXXX         Consumer             PR          2679 Rustic Loop             725.0              2         Fitness  18.279451  -66.037064  Pacific Asia     Bikaner         India              19492         1/13/2018 12:27     75939                    1360            16.389999                      0.05         179254                    327.75                    -0.80                    1  327.75        311.359985             -249.089996      South Asia         Rajastán          PENDING            NaN             1360                   73                  NaN  http://images.acmesports.sports/Smart+watch   Smart watch          327.75               0            1/18/2018 12:27  Standard Class
2      CASH                         4                              4        -247.779999          309.720001  Shipping on time                   0           73  Sporting Goods      San Jose          EE. UU.      XXXXXXXXX        Gillian        19491      Maldonado         XXXXXXXXX         Consumer             CA      8510 Round Bear Gate           95125.0              2         Fitness  37.292233 -121.881279  Pacific Asia     Bikaner         India              19491         1/13/2018 12:06     75938                    1360            18.030001                      0.06         179253                    327.75                    -0.80                    1  327.75        309.720001             -247.779999      South Asia         Rajastán           CLOSED            NaN             1360                   73                  NaN  http://images.acmesports.sports/Smart+watch   Smart watch          327.75               0            1/17/2018 12:06  Standard Class
3     DEBIT                         3                              4          22.860001          304.809998  Advance shipping                   0           73  Sporting Goods   Los Angeles          EE. UU.      XXXXXXXXX           Tana        19490           Tate         XXXXXXXXX      Home Office             CA           3200 Amber Bend           90027.0              2         Fitness  34.125946 -118.291016  Pacific Asia  Townsville     Australia              19490         1/13/2018 11:45     75937                    1360            22.940001                      0.07         179252                    327.75                     0.08                    1  327.75        304.809998               22.860001         Oceania       Queensland         COMPLETE            NaN             1360                   73                  NaN  http://images.acmesports.sports/Smart+watch   Smart watch          327.75               0            1/16/2018 11:45  Standard Class
4   PAYMENT                         2                              4         134.210007          298.250000  Advance shipping                   0           73  Sporting Goods        Caguas      Puerto Rico      XXXXXXXXX           Orli        19489      Hendricks         XXXXXXXXX        Corporate             PR  8671 Iron Anchor Corners             725.0              2         Fitness  18.253769  -66.037048  Pacific Asia  Townsville     Australia              19489         1/13/2018 11:24     75936                    1360            29.500000                      0.09         179251                    327.75                     0.45                    1  327.75        298.250000              134.210007         Oceania       Queensland  PENDING_PAYMENT            NaN             1360                   73                  NaN  http://images.acmesports.sports/Smart+watch   Smart watch          327.75               0            1/15/2018 11:24  Standard Class

In [5]:
clean_df.columns.tolist()

['Type',
 'Days for shipping (real)',
 'Days for shipment (scheduled)',
 'Benefit per order',
 'Sales per customer',
 'Delivery Status',
 'Late_delivery_risk',
 'Category Id',
 'Category Name',
 'Customer City',
 'Customer Country',
 'Customer Email',
 'Customer Fname',
 'Customer Id',
 'Customer Lname',
 'Customer Password',
 'Customer Segment',
 'Customer State',
 'Customer Street',
 'Customer Zipcode',
 'Department Id',
 'Department Name',
 'Latitude',
 'Longitude',
 'Market',
 'Order City',
 'Order Country',
 'Order Customer Id',
 'order date (DateOrders)',
 'Order Id',
 'Order Item Cardprod Id',
 'Order Item Discount',
 'Order Item Discount Rate',
 'Order Item Id',
 'Order Item Product Price',
 'Order Item Profit Ratio',
 'Order Item Quantity',
 'Sales',
 'Order Item Total',
 'Order Profit Per Order',
 'Order Region',
 'Order State',
 'Order Status',
 'Order Zipcode',
 'Product Card Id',
 'Product Category Id',
 'Product Description',
 'Product Image',
 'Product Name',
 'Product Price',
 'Product Status',
 'shipping date (DateOrders)',
 'Shipping Mode']

In [6]:
clean_df.columns = (
    clean_df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("(", "", regex=False)
    .str.replace(")", "", regex=False)
    .str.replace("-", "_")
)

In [7]:
clean_df.columns.tolist()

['type',
 'days_for_shipping_real',
 'days_for_shipment_scheduled',
 'benefit_per_order',
 'sales_per_customer',
 'delivery_status',
 'late_delivery_risk',
 'category_id',
 'category_name',
 'customer_city',
 'customer_country',
 'customer_email',
 'customer_fname',
 'customer_id',
 'customer_lname',
 'customer_password',
 'customer_segment',
 'customer_state',
 'customer_street',
 'customer_zipcode',
 'department_id',
 'department_name',
 'latitude',
 'longitude',
 'market',
 'order_city',
 'order_country',
 'order_customer_id',
 'order_date_dateorders',
 'order_id',
 'order_item_cardprod_id',
 'order_item_discount',
 'order_item_discount_rate',
 'order_item_id',
 'order_item_product_price',
 'order_item_profit_ratio',
 'order_item_quantity',
 'sales',
 'order_item_total',
 'order_profit_per_order',
 'order_region',
 'order_state',
 'order_status',
 'order_zipcode',
 'product_card_id',
 'product_category_id',
 'product_description',
 'product_image',
 'product_name',
 'product_price',
 'product_status',
 'shipping_date_dateorders',
 'shipping_mode']

In [8]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   type                         180519 non-null  object
 1   days_for_shipping_real       180519 non-null  int64
 2   days_for_shipment_scheduled  180519 non-null  int64
 3   benefit_per_order            180519 non-null  float64
 4   sales_per_customer           180519 non-null  float64
 5   delivery_status              180519 non-null  object
 6   late_delivery_risk           180519 non-null  int64
 7   category_id                  180519 non-null  int64
 8   category_name                180519 non-null  object
 9   customer_city                180519 non-null  object
 10  customer_country             180519 non-null  object
 11  customer_email               180519 non-null  object
 12  customer_fname               180519 non-null  object
 13  customer_id                  180519 non-null  int64
 14  customer_lname               180511 non-null  object
 15  customer_password            180519 non-null  object
 16  customer_segment             180519 non-null  object
 17  customer_state               180519 non-null  object
 18  customer_street              180519 non-null  object
 19  customer_zipcode             180516 non-null  float64
 20  department_id                180519 non-null  int64
 21  department_name              180519 non-null  object
 22  latitude                     180519 non-null  float64
 23  longitude                    180519 non-null  float64
 24  market                       180519 non-null  object
 25  order_city                   180519 non-null  object
 26  order_country                180519 non-null  object
 27  order_customer_id            180519 non-null  int64
 28  order_date_dateorders        180519 non-null  object
 29  order_id                     180519 non-null  int64
 30  order_item_cardprod_id       180519 non-null  int64
 31  order_item_discount          180519 non-null  float64
 32  order_item_discount_rate     180519 non-null  float64
 33  order_item_id                180519 non-null  int64
 34  order_item_product_price     180519 non-null  float64
 35  order_item_profit_ratio      180519 non-null  float64
 36  order_item_quantity          180519 non-null  int64
 37  sales                        180519 non-null  float64
 38  order_item_total             180519 non-null  float64
 39  order_profit_per_order       180519 non-null  float64
 40  order_region                 180519 non-null  object
 41  order_state                  180519 non-null  object
 42  order_status                 180519 non-null  object
 43  order_zipcode                24840 non-null   float64
 44  product_card_id              180519 non-null  int64
 45  product_category_id          180519 non-null  int64
 46  product_description          0 non-null       float64
 47  product_image                180519 non-null  object
 48  product_name                 180519 non-null  object
 49  product_price                180519 non-null  float64
 50  product_status               180519 non-null  int64
 51  shipping_date_dateorders     180519 non-null  object
 52  shipping_mode                180519 non-null  object
dtypes: float64(15), int64(14), object(24)
memory usage: 73.0+ MB

In [9]:
clean_df.isnull().sum().sort_values(ascending=False)

product_description            180519
order_zipcode                  155679
customer_lname                      8
customer_zipcode                    3
type                                0
order_profit_per_order              0
order_item_cardprod_id              0
order_item_discount                 0
order_item_discount_rate            0
order_item_id                       0
order_item_product_price            0
order_item_profit_ratio             0
order_item_quantity                 0
sales                               0
order_item_total                    0
order_region                        0
order_date_dateorders               0
order_state                         0
order_status                        0
product_card_id                     0
product_category_id                 0
product_image                       0
product_name                        0
product_price                       0
product_status                      0
shipping_date_dateorders            0
order_id                            0
order_country                       0
order_customer_id                   0
customer_fname                      0
days_for_shipment_scheduled         0
benefit_per_order                   0
sales_per_customer                  0
delivery_status                     0
late_delivery_risk                  0
category_id                         0
category_name                       0
customer_city                       0
customer_country                    0
customer_email                      0
customer_id                         0
days_for_shipping_real              0
customer_password                   0
customer_segment                    0
customer_state                      0
customer_street                     0
department_id                       0
department_name                     0
latitude                            0
longitude                           0
market                              0
order_city                          0
shipping_mode                       0
dtype: int64

In [10]:
(clean_df.isnull().sum()/len(clean_df)*100).round(2).sort_values(ascending=False)

product_description            100.00
order_zipcode                   86.24
type                             0.00
order_profit_per_order           0.00
order_id                         0.00
order_item_cardprod_id           0.00
order_item_discount              0.00
order_item_discount_rate         0.00
order_item_id                    0.00
order_item_product_price         0.00
order_item_profit_ratio          0.00
order_item_quantity              0.00
sales                            0.00
order_item_total                 0.00
order_region                     0.00
order_customer_id                0.00
order_state                      0.00
order_status                     0.00
product_card_id                  0.00
product_category_id              0.00
product_image                    0.00
product_name                     0.00
product_price                    0.00
product_status                   0.00
shipping_date_dateorders         0.00
order_date_dateorders            0.00
order_country                    0.00
days_for_shipping_real           0.00
order_city                       0.00
days_for_shipment_scheduled      0.00
benefit_per_order                0.00
sales_per_customer               0.00
delivery_status                  0.00
late_delivery_risk               0.00
category_id                      0.00
category_name                    0.00
customer_city                    0.00
customer_country                 0.00
customer_email                   0.00
customer_fname                   0.00
customer_id                      0.00
customer_lname                   0.00
customer_password                0.00
customer_segment                 0.00
customer_state                   0.00
customer_street                  0.00
customer_zipcode                 0.00
department_id                    0.00
department_name                  0.00
latitude                         0.00
longitude                        0.00
market                           0.00
shipping_mode                    0.00
dtype: float64

In [11]:
clean_df.duplicated().sum()

np.int64(0)

In [12]:
clean_df = clean_df.drop_duplicates()

print(clean_df.shape)

(180519, 53)

In [13]:
clean_df.select_dtypes(include="object").columns

Index(['type', 'delivery_status', 'category_name', 'customer_city', 'customer_country', 'customer_email', 'customer_fname', 'customer_lname', 'customer_password', 'customer_segment', 'customer_state', 'customer_street', 'department_name', 'market', 'order_city', 'order_country', 'order_date_dateorders', 'order_region', 'order_state', 'order_status', 'product_image', 'product_name', 'shipping_date_dateorders', 'shipping_mode'], dtype='object')

In [14]:
object_columns = clean_df.select_dtypes(include="object").columns

clean_df[object_columns] = clean_df[object_columns].apply(
    lambda x: x.str.strip() if x.dtype == "object" else x
)

In [15]:
clean_df.head()

       type  days_for_shipping_real  days_for_shipment_scheduled  benefit_per_order  sales_per_customer   delivery_status  late_delivery_risk  category_id   category_name customer_city customer_country customer_email customer_fname  customer_id customer_lname customer_password customer_segment customer_state           customer_street  customer_zipcode  department_id department_name   latitude   longitude        market  order_city order_country  order_customer_id order_date_dateorders  order_id  order_item_cardprod_id  order_item_discount  order_item_discount_rate  order_item_id  order_item_product_price  order_item_profit_ratio  order_item_quantity   sales  order_item_total  order_profit_per_order    order_region      order_state     order_status  order_zipcode  product_card_id  product_category_id  product_description                                product_image product_name  product_price  product_status shipping_date_dateorders   shipping_mode
0     DEBIT                       3                            4          91.250000          314.640015  Advance shipping                   0           73  Sporting Goods        Caguas      Puerto Rico      XXXXXXXXX          Cally        20755       Holloway         XXXXXXXXX         Consumer             PR  5365 Noble Nectar Island             725.0              2         Fitness  18.251453  -66.037056  Pacific Asia      Bekasi     Indonesia              20755       1/31/2018 22:56     77202                    1360            13.110000                      0.04         180517                    327.75                     0.29                    1  327.75        314.640015               91.250000  Southeast Asia  Java Occidental         COMPLETE            NaN             1360                   73                  NaN  http://images.acmesports.sports/Smart+watch  Smart watch         327.75               0           2/3/2018 22:56  Standard Class
1  TRANSFER                       5                            4        -249.089996          311.359985     Late delivery                   1           73  Sporting Goods        Caguas      Puerto Rico      XXXXXXXXX          Irene        19492           Luna         XXXXXXXXX         Consumer             PR          2679 Rustic Loop             725.0              2         Fitness  18.279451  -66.037064  Pacific Asia     Bikaner         India              19492       1/13/2018 12:27     75939                    1360            16.389999                      0.05         179254                    327.75                    -0.80                    1  327.75        311.359985             -249.089996      South Asia         Rajastán          PENDING            NaN             1360                   73                  NaN  http://images.acmesports.sports/Smart+watch  Smart watch         327.75               0          1/18/2018 12:27  Standard Class
2      CASH                       4                            4        -247.779999          309.720001  Shipping on time                   0           73  Sporting Goods      San Jose          EE. UU.      XXXXXXXXX        Gillian        19491      Maldonado         XXXXXXXXX         Consumer             CA      8510 Round Bear Gate           95125.0              2         Fitness  37.292233 -121.881279  Pacific Asia     Bikaner         India              19491       1/13/2018 12:06     75938                    1360            18.030001                      0.06         179253                    327.75                    -0.80                    1  327.75        309.720001             -247.779999      South Asia         Rajastán           CLOSED            NaN             1360                   73                  NaN  http://images.acmesports.sports/Smart+watch  Smart watch         327.75               0          1/17/2018 12:06  Standard Class
3     DEBIT                       3                            4          22.860001          304.809998  Advance shipping                   0           73  Sporting Goods   Los Angeles          EE. UU.      XXXXXXXXX           Tana        19490           Tate         XXXXXXXXX      Home Office             CA           3200 Amber Bend           90027.0              2         Fitness  34.125946 -118.291016  Pacific Asia  Townsville     Australia              19490       1/13/2018 11:45     75937                    1360            22.940001                      0.07         179252                    327.75                     0.08                    1  327.75        304.809998               22.860001         Oceania       Queensland         COMPLETE            NaN             1360                   73                  NaN  http://images.acmesports.sports/Smart+watch  Smart watch         327.75               0          1/16/2018 11:45  Standard Class
4   PAYMENT                       2                            4         134.210007          298.250000  Advance shipping                   0           73  Sporting Goods        Caguas      Puerto Rico      XXXXXXXXX           Orli        19489      Hendricks         XXXXXXXXX        Corporate             PR  8671 Iron Anchor Corners             725.0              2         Fitness  18.253769  -66.037048  Pacific Asia  Townsville     Australia              19489       1/13/2018 11:24     75936                    1360            29.500000                      0.09         179251                    327.75                     0.45                    1  327.75        298.250000              134.210007         Oceania       Queensland  PENDING_PAYMENT            NaN             1360                   73                  NaN  http://images.acmesports.sports/Smart+watch  Smart watch         327.75               0          1/15/2018 11:24  Standard Class

In [16]:
clean_df.select_dtypes(include=["int64","float64"]).describe().T

                                count          mean           std          min           25%           50%            75%            max
days_for_shipping_real       180519.0      3.497654      1.623722     0.000000      2.000000      3.000000       5.000000       6.000000
days_for_shipment_scheduled  180519.0      2.931847      1.374449     0.000000      2.000000      4.000000       4.000000       4.000000
benefit_per_order            180519.0     21.974989    104.433526 -4274.979980      7.000000     31.520000      64.800003     911.799988
sales_per_customer           180519.0    183.107609    120.043670     7.490000    104.379997    163.990005     247.399994    1939.989990
late_delivery_risk           180519.0      0.548291      0.497664     0.000000      0.000000      1.000000       1.000000       1.000000
category_id                  180519.0     31.851451     15.640064     2.000000     18.000000     29.000000      45.000000      76.000000
customer_id                  180519.0   6691.379495   4162.918106     1.000000   3258.500000   6457.000000    9779.000000   20757.000000
customer_zipcode             180516.0  35921.126914  37542.461122   603.000000    725.000000  19380.000000   78207.000000   99205.000000
department_id                180519.0      5.443460      1.629246     2.000000      4.000000      5.000000       7.000000      12.000000
latitude                     180519.0     29.719955      9.813646   -33.937553     18.265432     33.144863      39.279617      48.781933
longitude                    180519.0    -84.915675     21.433241  -158.025986    -98.446312    -76.847908     -66.370583     115.263077
order_customer_id            180519.0   6691.379495   4162.918106     1.000000   3258.500000   6457.000000    9779.000000   20757.000000
order_id                     180519.0  36221.894903  21045.379569     1.000000  18057.000000  36140.000000   54144.000000   77204.000000
order_item_cardprod_id       180519.0    692.509764    336.446807    19.000000    403.000000    627.000000    1004.000000    1363.000000
order_item_discount          180519.0     20.664741     21.800901     0.000000      5.400000     14.000000      29.990000     500.000000
order_item_discount_rate     180519.0      0.101668      0.070415     0.000000      0.040000      0.100000       0.160000       0.250000
order_item_id                180519.0  90260.000000  52111.490959     1.000000  45130.500000  90260.000000  135389.500000  180519.000000
order_item_product_price     180519.0    141.232550    139.732492     9.990000     50.000000     59.990002     199.990005    1999.989990
order_item_profit_ratio      180519.0      0.120647      0.466796    -2.750000      0.080000      0.270000       0.360000       0.500000
order_item_quantity          180519.0      2.127638      1.453451     1.000000      1.000000      1.000000       3.000000       5.000000
sales                        180519.0    203.772096    132.273077     9.990000    119.980003    199.919998     299.950012    1999.989990
order_item_total             180519.0    183.107609    120.043670     7.490000    104.379997    163.990005     247.399994    1939.989990
order_profit_per_order       180519.0     21.974989    104.433526 -4274.979980      7.000000     31.520000      64.800003     911.799988
order_zipcode                 24840.0  55426.132327  31919.279101  1040.000000  23464.000000  59405.000000   90008.000000   99301.000000
product_card_id              180519.0    692.509764    336.446807    19.000000    403.000000    627.000000    1004.000000    1363.000000
product_category_id          180519.0     31.851451     15.640064     2.000000     18.000000     29.000000      45.000000      76.000000
product_description               0.0           NaN           NaN          NaN           NaN           NaN            NaN            NaN
product_price                180519.0    141.232550    139.732492     9.990000     50.000000     59.990002     199.990005    1999.989990
product_status               180519.0      0.000000      0.000000     0.000000      0.000000      0.000000       0.000000       0.000000

In [17]:
date_columns = [col for col in clean_df.columns if "date" in col]

date_columns

['order_date_dateorders', 'shipping_date_dateorders']

In [18]:
for col in date_columns:
    clean_df[col] = pd.to_datetime(clean_df[col], errors="coerce")

In [19]:
clean_df[date_columns].dtypes

order_date_dateorders       datetime64[ns]
shipping_date_dateorders    datetime64[ns]
dtype: object

In [20]:
clean_df.isnull().sum().sort_values(ascending=False)

product_description            180519
order_zipcode                  155679
customer_lname                      8
customer_zipcode                    3
type                                0
order_profit_per_order              0
order_item_cardprod_id              0
order_item_discount                 0
order_item_discount_rate            0
order_item_id                       0
order_item_product_price            0
order_item_profit_ratio             0
order_item_quantity                 0
sales                               0
order_item_total                    0
order_region                        0
order_date_dateorders               0
order_state                         0
order_status                        0
product_card_id                     0
product_category_id                 0
product_image                       0
product_name                        0
product_price                       0
product_status                      0
shipping_date_dateorders            0
order_id                            0
order_country                       0
order_customer_id                   0
customer_fname                      0
days_for_shipment_scheduled         0
benefit_per_order                   0
sales_per_customer                  0
delivery_status                     0
late_delivery_risk                  0
category_id                         0
category_name                       0
customer_city                       0
customer_country                    0
customer_email                      0
customer_id                         0
days_for_shipping_real              0
customer_password                   0
customer_segment                    0
customer_state                      0
customer_street                     0
department_id                       0
department_name                     0
latitude                            0
longitude                           0
market                              0
order_city                          0
shipping_mode                       0
dtype: int64

In [21]:
clean_df.describe(include="all").T

                                count unique                                                top    freq                           mean                  min                  25%                  50%                  75%                  max           std
type                           180519      4                                              DEBIT   69295                            NaN                  NaN                  NaN                  NaN                  NaN                  NaN           NaN
days_for_shipping_real       180519.0    NaN                                                NaN     NaN                       3.497654                  0.0                  2.0                  3.0                  5.0                  6.0      1.623722
days_for_shipment_scheduled  180519.0    NaN                                                NaN     NaN                       2.931847                  0.0                  2.0                  4.0                  4.0                  4.0      1.374449
benefit_per_order            180519.0    NaN                                                NaN     NaN                      21.974989          -4274.97998                  7.0                31.52            64.800003           911.799988    104.433526
sales_per_customer           180519.0    NaN                                                NaN     NaN                     183.107609                 7.49           104.379997           163.990005           247.399994           1939.98999     120.04367
delivery_status                180519      4                                      Late delivery   98977                            NaN                  NaN                  NaN                  NaN                  NaN                  NaN           NaN
late_delivery_risk           180519.0    NaN                                                NaN     NaN                       0.548291                  0.0                  0.0                  1.0                  1.0                  1.0      0.497664
category_id                  180519.0    NaN                                                NaN     NaN                      31.851451                  2.0                 18.0                 29.0                 45.0                 76.0     15.640064
category_name                  180519     50                                             Cleats   24551                            NaN                  NaN                  NaN                  NaN                  NaN                  NaN           NaN
customer_city                  180519    563                                             Caguas   66770                            NaN                  NaN                  NaN                  NaN                  NaN                  NaN           NaN
customer_country               180519      2                                            EE. UU.  111146                            NaN                  NaN                  NaN                  NaN                  NaN                  NaN           NaN
customer_email                 180519      1                                          XXXXXXXXX  180519                            NaN                  NaN                  NaN                  NaN                  NaN                  NaN           NaN
customer_fname                 180519    782                                               Mary   65150                            NaN                  NaN                  NaN                  NaN                  NaN                  NaN           NaN
customer_id                  180519.0    NaN                                                NaN     NaN                    6691.379495                  1.0               3258.5               6457.0               9779.0              20757.0   4162.918106
customer_lname                 180511   1109                                              Smith   64104                            NaN                  NaN                  NaN                  NaN                  NaN                  NaN           NaN
customer_password              180519      1                                          XXXXXXXXX  180519                            NaN                  NaN                  NaN                  NaN                  NaN                  NaN           NaN
customer_segment               180519      3                                           Consumer   93504                            NaN                  NaN                  NaN                  NaN                  NaN                  NaN           NaN
customer_state                 180519     46                                                 PR   69373                            NaN                  NaN                  NaN                  NaN                  NaN                  NaN           NaN
customer_street                180519   6953                            9126 Wishing Expressway     124                            NaN                  NaN                  NaN                  NaN                  NaN                  NaN           NaN
customer_zipcode             180516.0    NaN                                                NaN     NaN                   35921.126914                603.0                725.0              19380.0              78207.0              99205.0  37542.461122
department_id                180519.0    NaN                                                NaN     NaN                        5.44346                  2.0                  4.0                  5.0                  7.0                 12.0      1.629246
department_name                180519     11                                           Fan Shop   66861                            NaN                  NaN                  NaN                  NaN                  NaN                  NaN           NaN
latitude                     180519.0    NaN                                                NaN     NaN                      29.719955           -33.937553            18.265432            33.144863            39.279617            48.781933      9.813646
longitude                    180519.0    NaN                                                NaN     NaN                     -84.915675          -158.025986           -98.446312           -76.847908           -66.370583           115.263077     21.433241
market                         180519      5                                              LATAM   51594                            NaN                  NaN                  NaN                  NaN                  NaN                  NaN           NaN
order_city                     180519   3597                                      Santo Domingo    2211                            NaN                  NaN                  NaN                  NaN                  NaN                  NaN           NaN
order_country                  180519    164                                     Estados Unidos   24840                            NaN                  NaN                  NaN                  NaN                  NaN                  NaN           NaN
order_customer_id            180519.0    NaN                                                NaN     NaN                    6691.379495                  1.0               3258.5               6457.0               9779.0              20757.0   4162.918106
order_date_dateorders          180519    NaN                                                NaN     NaN  2016-06-12 17:47:04.669868544  2015-01-01 00:00:00  2015-09-21 13:49:00  2016-06-11 13:06:00  2017-03-01 08:42:00  2018-01-31 23:38:00           NaN
order_id                     180519.0    NaN                                                NaN     NaN                   36221.894903                  1.0              18057.0              36140.0              54144.0              77204.0  21045.379569
order_item_cardprod_id       180519.0    NaN                                                NaN     NaN                     692.509764                 19.0                403.0                627.0               1004.0               1363.0    336.446807
order_item_discount          180519.0    NaN                                                NaN     NaN                      20.664741                  0.0                  5.4                 14.0                29.99                500.0     21.800901
order_item_discount_rate     180519.0    NaN                                                NaN     NaN                       0.101668                  0.0                 0.04                  0.1                 0.16                 0.25      0.070415
order_item_id                180519.0    NaN                                                NaN     NaN                        90260.0                  1.0              45130.5              90260.0             135389.5             180519.0  52111.490959
order_item_product_price     180519.0    NaN                                                NaN     NaN                      141.23255                 9.99                 50.0            59.990002           199.990005           1999.98999    139.732492
order_item_profit_ratio      180519.0    NaN                                                NaN     NaN                       0.120647                -2.75                 0.08                 0.27                 0.36                  0.5      0.466796
order_item_quantity          180519.0    NaN                                                NaN     NaN                       2.127638                  1.0                  1.0                  1.0                  3.0                  5.0      1.453451
sales                        180519.0    NaN                                                NaN     NaN                     203.772096                 9.99           119.980003           199.919998           299.950012           1999.98999    132.273077
order_item_total             180519.0    NaN                                                NaN     NaN                     183.107609                 7.49           104.379997           163.990005           247.399994           1939.98999     120.04367
order_profit_per_order       180519.0    NaN                                                NaN     NaN                      21.974989          -4274.97998                  7.0                31.52            64.800003           911.799988    104.433526
order_region                   180519     23                                    Central America   28341                            NaN                  NaN                  NaN                  NaN                  NaN                  NaN           NaN
order_state                    180519   1089                                         Inglaterra    6722                            NaN                  NaN                  NaN                  NaN                  NaN                  NaN           NaN
order_status                   180519      9                                           COMPLETE   59491                            NaN                  NaN                  NaN                  NaN                  NaN                  NaN           NaN
order_zipcode                 24840.0    NaN                                                NaN     NaN                   55426.132327               1040.0              23464.0              59405.0              90008.0              99301.0  31919.279101
product_card_id              180519.0    NaN                                                NaN     NaN                     692.509764                 19.0                403.0                627.0               1004.0               1363.0    336.446807
product_category_id          180519.0    NaN                                                NaN     NaN                      31.851451                  2.0                 18.0                 29.0                 45.0                 76.0     15.640064
product_description               0.0    NaN                                                NaN     NaN                            NaN                  NaN                  NaN                  NaN                  NaN                  NaN           NaN
product_image                  180519    118  http://images.acmesports.sports/Perfect+Fitnes...   24515                            NaN                  NaN                  NaN                  NaN                  NaN                  NaN           NaN
product_name                   180519    118                   Perfect Fitness Perfect Rip Deck   24515                            NaN                  NaN                  NaN                  NaN                  NaN                  NaN           NaN
product_price                180519.0    NaN                                                NaN     NaN                      141.23255                 9.99                 50.0            59.990002           199.990005           1999.98999    139.732492
product_status               180519.0    NaN                                                NaN     NaN                            0.0                  0.0                  0.0                  0.0                  0.0                  0.0           0.0
shipping_date_dateorders       180519    NaN                                                NaN     NaN  2016-06-16 05:45:23.202433024  2015-01-03 00:00:00  2015-09-25 06:59:00  2016-06-15 08:32:00  2017-03-04 21:29:00  2018-02-06 22:14:00           NaN
shipping_mode                  180519      4                                     Standard Class  107752                            NaN                  NaN                  NaN                  NaN                  NaN                  NaN           NaN

In [22]:
clean_df.shape

(180519, 53)

In [23]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   type                         180519 non-null  object
 1   days_for_shipping_real       180519 non-null  int64
 2   days_for_shipment_scheduled  180519 non-null  int64
 3   benefit_per_order            180519 non-null  float64
 4   sales_per_customer           180519 non-null  float64
 5   delivery_status              180519 non-null  object
 6   late_delivery_risk           180519 non-null  int64
 7   category_id                  180519 non-null  int64
 8   category_name                180519 non-null  object
 9   customer_city                180519 non-null  object
 10  customer_country             180519 non-null  object
 11  customer_email               180519 non-null  object
 12  customer_fname               180519 non-null  object
 13  customer_id                  180519 non-null  int64
 14  customer_lname               180511 non-null  object
 15  customer_password            180519 non-null  object
 16  customer_segment             180519 non-null  object
 17  customer_state               180519 non-null  object
 18  customer_street              180519 non-null  object
 19  customer_zipcode             180516 non-null  float64
 20  department_id                180519 non-null  int64
 21  department_name              180519 non-null  object
 22  latitude                     180519 non-null  float64
 23  longitude                    180519 non-null  float64
 24  market                       180519 non-null  object
 25  order_city                   180519 non-null  object
 26  order_country                180519 non-null  object
 27  order_customer_id            180519 non-null  int64
 28  order_date_dateorders        180519 non-null  datetime64[ns]
 29  order_id                     180519 non-null  int64
 30  order_item_cardprod_id       180519 non-null  int64
 31  order_item_discount          180519 non-null  float64
 32  order_item_discount_rate     180519 non-null  float64
 33  order_item_id                180519 non-null  int64
 34  order_item_product_price     180519 non-null  float64
 35  order_item_profit_ratio      180519 non-null  float64
 36  order_item_quantity          180519 non-null  int64
 37  sales                        180519 non-null  float64
 38  order_item_total             180519 non-null  float64
 39  order_profit_per_order       180519 non-null  float64
 40  order_region                 180519 non-null  object
 41  order_state                  180519 non-null  object
 42  order_status                 180519 non-null  object
 43  order_zipcode                24840 non-null   float64
 44  product_card_id              180519 non-null  int64
 45  product_category_id          180519 non-null  int64
 46  product_description          0 non-null       float64
 47  product_image                180519 non-null  object
 48  product_name                 180519 non-null  object
 49  product_price                180519 non-null  float64
 50  product_status               180519 non-null  int64
 51  shipping_date_dateorders     180519 non-null  datetime64[ns]
 52  shipping_mode                180519 non-null  object
dtypes: datetime64[ns](2), float64(15), int64(14), object(22)
memory usage: 73.0+ MB

In [24]:
clean_df.to_csv(
    "../data/processed/cleaned_supply_chain_dataset.csv",
    index=False
)

In [25]:
print("Cleaned dataset exported successfully.")

Cleaned dataset exported successfully.

# Data Cleaning Summary

## Completed Tasks

- Loaded the raw dataset
- Created a working copy
- Standardized column names
- Checked missing values
- Removed duplicate records
- Trimmed unnecessary whitespace from text columns
- Validated date columns
- Reviewed numerical and categorical data
- Exported the cleaned dataset

---

## Output

The cleaned dataset has been saved in the `data/processed/` directory and will be used for feature engineering, SQL analysis, Excel dashboards, and Tableau dashboards.